version: 2
registries:
  github-packages:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.NPM_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - github-packages
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 5
    labels:
      - "motor-update"
    commit-message:
      prefix: "chore"
    allow:
      - dependency-name: "@Immoral-marketing/motor-blog"